name: sync-repo
on:
    push:
        branches:
            - main

jobs:
    sync:
        name: Sync
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install git
              run: sudo apt update && echo Y | sudo apt install git
              
            - name: Clone repo
              run: git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/zubeyiro/private-repo.git
            
            - name: List directory
              run: ls -all
